name: blind_ai
description: "BlindAI - Perceive with intelligence."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  animations: ^2.2.0
  google_fonts: ^8.1.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  equatable: ^2.0.8
  get_it: ^9.2.1
  dartz: ^0.10.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0F0F15"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true
