// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6mzIa6w3z8DTxTd-8L1CcTnF7K98Pzb8',
    appId: '1:322431065959:web:d42fbc38539beb2c2559c2',
    messagingSenderId: '322431065959',
    projectId: 'blindai-37ddc',
    authDomain: 'blindai-37ddc.firebaseapp.com',
    storageBucket: 'blindai-37ddc.firebasestorage.app',
    measurementId: 'G-J9VHN35LNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1IzpTIjG0Ja3pwdw9-dBCsuj4hWoxLo',
    appId: '1:322431065959:android:7576d9a4535581672559c2',
    messagingSenderId: '322431065959',
    projectId: 'blindai-37ddc',
    storageBucket: 'blindai-37ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBQs84aalvIdLqjR7lZy8tKm94P1iF50k',
    appId: '1:322431065959:ios:f87da2192efc00b52559c2',
    messagingSenderId: '322431065959',
    projectId: 'blindai-37ddc',
    storageBucket: 'blindai-37ddc.firebasestorage.app',
    iosBundleId: 'com.blindai.blindAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBQs84aalvIdLqjR7lZy8tKm94P1iF50k',
    appId: '1:322431065959:ios:f87da2192efc00b52559c2',
    messagingSenderId: '322431065959',
    projectId: 'blindai-37ddc',
    storageBucket: 'blindai-37ddc.firebasestorage.app',
    iosBundleId: 'com.blindai.blindAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6mzIa6w3z8DTxTd-8L1CcTnF7K98Pzb8',
    appId: '1:322431065959:web:6030ccfddd4243cd2559c2',
    messagingSenderId: '322431065959',
    projectId: 'blindai-37ddc',
    authDomain: 'blindai-37ddc.firebaseapp.com',
    storageBucket: 'blindai-37ddc.firebasestorage.app',
    measurementId: 'G-5WG4196X6S',
  );
}
